' Perceptron Neural Network Diagram
' This PlantUML diagram visualizes a simple perceptron neural network with three layers:
' - Input layer (layer 1) with three input nodes (x1, x2, x3)
' - Hidden layer (layer 2) with three nodes (a12, a22, a32)
' - Output layer (layer 3) with one output node (O)
' 
' Reference: https://gist.github.com/thigm85/5653059
digraph G {

    rankdir=LR
	splines=line
        
    node [fixedsize=true, label=""];


	subgraph cluster_1 {
		color=white;
		node [style=solid,color=Blue, shape=circle];
		x1 [label="x1"];
        x2 [label="x2"];
        x3 [label="x3"];
		label = "input layer";
	}

	subgraph cluster_2 {
		color=white;
		node [style=solid,color=seagreen2, shape=circle];
		Z [label="z"];
	}

	subgraph cluster_3 {
		color=white;
		node [style=solid,color=Red, shape=circle];
		Y [label="y"];
		label="output layer";
	}


    x1 -> Z; 
    x2 -> Z;
    x3 -> Z; 
    Z -> Y [label="y = g(z)"];

    labeljust="c";
    label = <<table border="0" cellborder="0" cellspacing="0">
                <tr><td><font point-size="20">z = w0 + w1*x1 + w2*x2 + w3*x3</font></td></tr>
             </table>>;

}